<?php
include("connectdb.php");
//require("fpdf/fpdf.php");
$count = 0;
$pg = 0;
$cn = 34;
$s1 = 0;
$s2 = 0;
$s3 = 0;
$s4 = 0;
$s5 = 0;
$s6 = 0;
$s7 = 0;
$s8 = 0;
$s9 = 0;
$s10 = 0;
$s11 = 0;
$s12 = 0;
$s13 = 0;
$s14 = 0;
$s15 = 0;
$s16 = 0;
$s17 = 0;
require("../html_table/html_table.php");
$cpdf = "<link rel='stylesheet' href='css/app.css'><link href='css/gapi.css' rel='stylesheet'>";
$cpdf .= "<table class='table' border='TR'>";
// $cpdf .= '<thead class="table-dark">';
// $cpdf .= '<tr>';
// $cpdf .= '<th scope="col" style="width: 30px;">Sr No 1.</th>';
// $cpdf .= '<th scope="col" style="width: 30px;">Sr No 2.</th>';
// $cpdf .= '<th scope="col" style="width: 30px;">Sr No 3.</th>';
// $cpdf .= '<th scope="col" style="width: 30px;">Sr No 4.</th>';
// $cpdf .= '<th scope="col" style="width: 30px;">Sr No 5.</th>';
// $cpdf .= '<th scope="col" style="width: 30px;">Sr No 6.</th>';
// $cpdf .=  "<td style='width: 10%;'>SalEmpNo</td>";
// $cpdf .=  "<td style='width: 30px;'>SalEmpNo</td>";
// $cpdf .=  "<td style='width: 30px;'>SalEmpNo</td>";
// $cpdf .=  "<td style='width: 30px;'>SalEmpNo</td>";
// $cpdf .=  "<td style='width: 30px;'>SalEmpNo</td>";
// $cpdf .=  "<td style='width: 30px;'>SalEmpNo</td>";
// $cpdf .=  "<td style='width: 30px;'>SalEmpNo</td>";
//$cpdf .=  "<td style='width: 30px;'>SalEmpNo</td>";
// $cpdf .=  "<td width='60' height='30'>Emp No.</td>";
//$cpdf .=  "<td width='30' height='30'>Date </td>";
// $cpdf .=  "<td width='70' height='30'>Emp Name</td>";
// $cpdf .=  "<td width='55' height='30'>Basic</td>";
// $cpdf .=  "<td width='42' height='30'>DA</td>";
// $cpdf .=  "<td width='42' height='30'>CLA</td>";
// $cpdf .=  "<td width='60' height='30'>HRA </td>";
// $cpdf .=  "<td width='45' height='30'>TA </td>";
// $cpdf .=  "<td width='60' height='30'>SP Pay </td>";
// $cpdf .=  "<td width='60' height='30'>DG Pay </td>";
// $cpdf .=  "<td width='60' height='30'>MA </td>";
// $cpdf .=  "<td width='60' height='30'>PT </td>";
// $cpdf .=  "<td width='100' height='30'>Total earn </td>";
// $cpdf .=  "<td width='100' height='30'>Total deduction </td>";
// $cpdf .=  "<td width='100' height='30'>N.P. </td>";

// $cpdf .= '</tr>';
// $cpdf .= '</thead>';
$cpdf .= '<tbody>';
$querys = "";
if ($_GET["eid"] == 0) {
    $querys .= "SELECT * FROM ttbsalarymaster WHERE year='" . $_GET["eye"] . "' AND SalMonthname = '" . $_GET["emo"] . "';";
} else {
    $querys .= "SELECT * FROM ttbsalarymaster WHERE year='" . $_GET["eye"] . "' AND SalMonthname = '" . $_GET["emo"] . "' AND SalEmpNo = '" . $_GET["eid"] . "';";
}
if ($results = mysqli_query($con, $querys)) {
    while ($erow = mysqli_fetch_array($results)) {
        if (($count % $cn) == 0) {
            $pg++;
            $cpdf .= '<tr>';
            $cpdf .=  "<td width='1' height='30'>&nbsp;</td>";
            $cpdf .=  "<td width='50' height='30'>Emp No.</td>";
            $cpdf .=  "<td width='180' height='30'>Emp Name</td>";
            $cpdf .=  "<td width='62' height='30'>Basic</td>";
            $cpdf .=  "<td width='44' height='30'>DA</td>";
            $cpdf .=  "<td width='39' height='30'>CLA</td>";
            $cpdf .=  "<td width='57' height='30'>HRA </td>";
            $cpdf .=  "<td width='42' height='30'>TA </td>";
            $cpdf .=  "<td width='54' height='30'>SP Pay </td>";
            $cpdf .=  "<td width='54' height='30'>DG Pay </td>";
            $cpdf .=  "<td width='57' height='30'>MA </td>";
            $cpdf .=  "<td width='57' height='30'>PT </td>";
            $cpdf .=  "<td width='52' height='30'>Arreas1 </td>";
            $cpdf .=  "<td width='52' height='30'>Arreas2 </td>";
            $cpdf .=  "<td width='52' height='30'>PF</td>";
            $cpdf .=  "<td width='44' height='30'>IT</td>";
            $cpdf .=  "<td width='39' height='30'>Other</td>";
            $cpdf .=  "<td width='70' height='30'>Total earn </td>";
            $cpdf .=  "<td width='70' height='30'>Total deduct </td>";
            $cpdf .=  "<td width='70' height='30'>Net Payable </td>";
            $cpdf .= '</tr>';
            // $cpdf .= "<br>";
            // $cpdf .= "<br>";
            // $cpdf .= "<br>";
        }
        $cpdf .=  "<tr>";
        $cpdf .=  "<td width='1' height='30'>&nbsp;</td>";
        $cpdf .=  "<td width='50' height='30'>" . $erow["SalEmpNo"] . "</td>";
        $cpdf .= "<td width='180' height='30'>" . $erow["SalEmpName"] . "</t>";
        $cpdf .=  "<td width='62' height='30'>" . $erow["SalBasic"] . "</td>";
        $cpdf .=  "<td width='44' height='30'>" . $erow["SalDA"] . "</td>";
        $cpdf .=  "<td width='39' height='30'>" . $erow["SalCLA"] . "</td>";
        $cpdf .=  "<td width='57' height='30'>" . $erow["SalHRA"] . " </td>";
        $cpdf .=  "<td width='42' height='30'>" . $erow["SalTA"] . " </td>";
        $cpdf .=  "<td width='54' height='30'>" . $erow["SalSPPay"] . "</td>";
        $cpdf .=  "<td width='54' height='30'>" . $erow["SalDGPay"] . " </td>";
        $cpdf .=  "<td width='57' height='30'>" . $erow["SalMA"] . " </td>";
        $cpdf .=  "<td width='57' height='30'>" . $erow["SalPTax"] . " </td>";
        $cpdf .=  "<td width='52' height='30'>" . $erow["SalArreas1"] . " </td>";
        $cpdf .=  "<td width='52' height='30'>" . $erow["SalArreas2"] . " </td>";
        $cpdf .=  "<td width='52' height='30'>" . $erow["SalPF"] . "</td>";
        $cpdf .=  "<td width='44' height='30'>" . $erow["SalIncomTax"] . "</td>";
        $cpdf .=  "<td width='39' height='30'>" . $erow["Salother"] . "</td>";
        $cpdf .=  "<td width='70' height='30'>" . $erow["SalTotalEarning"] . " </td>";
        $cpdf .=  "<td width='70' height='30'>" . $erow["SalTotalDeduction"] . " </td>";
        $cpdf .=  "<td width='70' height='30'>" . $erow["SalNetPayable"] . "</td>";
        $cpdf .= "</tr>";
        // $cpdf .= "<br>";
        $s1 += $erow["SalBasic"];
        $s2 += $erow["SalDA"];
        $s3 += $erow["SalCLA"];
        $s4 += $erow["SalHRA"];
        $s5 += $erow["SalTA"];
        $s6 += $erow["SalSPPay"];
        $s7 += $erow["SalDGPay"];
        $s8 += $erow["SalMA"];
        $s9 += $erow["SalPTax"];
        $s10 += $erow["SalArreas1"];
        $s11 += $erow["SalArreas2"];
        $s12 += $erow["SalTotalEarning"];
        $s13 += $erow["SalTotalDeduction"];
        $s14 += $erow["SalNetPayable"];
        $s15 += $erow["SalPF"];
        $s16 += $erow["SalIncomTax"];
        $s17 += $erow["Salother"];
        $count++;
    }
    if ($count == 0) {
        $cpdf .= '<tr>';
        $cpdf .=  "<td width='1' height='30'>&nbsp;</td>";
        $cpdf .=  "<td width='50' height='30'>Emp No.</td>";
        $cpdf .=  "<td width='180' height='30'>Emp Name</td>";
        $cpdf .=  "<td width='62' height='30'>Basic</td>";
        $cpdf .=  "<td width='44' height='30'>DA</td>";
        $cpdf .=  "<td width='39' height='30'>CLA</td>";
        $cpdf .=  "<td width='57' height='30'>HRA </td>";
        $cpdf .=  "<td width='42' height='30'>TA </td>";
        $cpdf .=  "<td width='54' height='30'>SP Pay </td>";
        $cpdf .=  "<td width='54' height='30'>DG Pay </td>";
        $cpdf .=  "<td width='57' height='30'>MA </td>";
        $cpdf .=  "<td width='57' height='30'>PT </td>";
        $cpdf .=  "<td width='52' height='30'>Arreas1 </td>";
        $cpdf .=  "<td width='52' height='30'>Arreas2 </td>";
        $cpdf .=  "<td width='52' height='30'>PF</td>";
        $cpdf .=  "<td width='44' height='30'>IT</td>";
        $cpdf .=  "<td width='39' height='30'>Other</td>";
        $cpdf .=  "<td width='70' height='30'>Total earn </td>";
        $cpdf .=  "<td width='70' height='30'>Total deduct </td>";
        $cpdf .=  "<td width='70' height='30'>Net Payable </td>";
        $cpdf .= '</tr>';
    }
    $cpdf .=  "<tr>";
    $cpdf .=  "<td width='1' height='30'>&nbsp;</td>";
    $cpdf .=  "<td width='50'>&nbsp;</td>";
    $cpdf .= "<td width='180' height='30'>SCHOOL TOTAL</t>";
    $cpdf .=  "<td width='62' height='30'>" . $s1 . "</td>";
    $cpdf .=  "<td width='44' height='30'>" . $s2 . "</td>";
    $cpdf .=  "<td width='39' height='30'>" . $s3 . "</td>";
    $cpdf .=  "<td width='57' height='30'>" . $s4 . " </td>";
    $cpdf .=  "<td width='42' height='30'>" . $s5 . " </td>";
    $cpdf .=  "<td width='54' height='30'>" . $s6 . "</td>";
    $cpdf .=  "<td width='54' height='30'>" . $s7 . " </td>";
    $cpdf .=  "<td width='57' height='30'>" . $s8 . " </td>";
    $cpdf .=  "<td width='57' height='30'>" . $s9 . " </td>";
    $cpdf .=  "<td width='52' height='30'>" . $s10 . " </td>";
    $cpdf .=  "<td width='52' height='30'>" . $s11 . " </td>";
    $cpdf .=  "<td width='52' height='30'>" . $s15 . "</td>";
    $cpdf .=  "<td width='44' height='30'>" . $s16 . "</td>";
    $cpdf .=  "<td width='39' height='30'>" . $s17 . "</td>";
    $cpdf .=  "<td width='70' height='30'>" . $s12 . " </td>";
    $cpdf .=  "<td width='70' height='30'>" . $s13 . " </td>";
    $cpdf .=  "<td width='70' height='30'>" . $s14 . "</td>";
    $cpdf .= "</tr>";
    $cpdf .= "<br>";
}
$cpdf .=  "</tbody>";
$cpdf .=  "</table>";
//echo $cpdf;
$slip = new PDF();
$slip->AddPage('L', "A4");
$slip->SetFont('Arial', '', 8);
$slip->WriteHTML($cpdf);
$slip->Output();
